//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CardSupport.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CardSupport")
#ifdef RESTRICT_CardSupport
#define INCLUDE_ALL_CardSupport 0
#else
#define INCLUDE_ALL_CardSupport 1
#endif
#undef RESTRICT_CardSupport

#if !defined (AppBaseCardSupport_) && (INCLUDE_ALL_CardSupport || defined(INCLUDE_AppBaseCardSupport))
#define AppBaseCardSupport_

@interface AppBaseCardSupport : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)getBandeiraWithNSString:(NSString *)numero;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseCardSupport)

FOUNDATION_EXPORT void AppBaseCardSupport_init(AppBaseCardSupport *self);

FOUNDATION_EXPORT AppBaseCardSupport *new_AppBaseCardSupport_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseCardSupport *create_AppBaseCardSupport_init(void);

FOUNDATION_EXPORT NSString *AppBaseCardSupport_getBandeiraWithNSString_(NSString *numero);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseCardSupport)

@compatibility_alias BrComMobilemindJ2objcPaymentsCardSupport AppBaseCardSupport;

#endif

#pragma pop_macro("INCLUDE_ALL_CardSupport")
