//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonBuilder.java
//

#ifndef JsonBuilder_H
#define JsonBuilder_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class GsonJsonElement;
@class GsonJsonObject;
@class JavaLangBoolean;
@class JavaLangCharacter;

@interface BrComMobilemindJ2objcJsonJsonBuilder : NSObject {
 @public
  GsonJsonObject *json_;
}

#pragma mark Public

- (instancetype __nonnull)init;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                      withJavaLangBoolean:(JavaLangBoolean *)value;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                    withJavaLangCharacter:(JavaLangCharacter *)character;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                 withBrComMobilemindJ2objcJsonJsonBuilder:(BrComMobilemindJ2objcJsonJsonBuilder *)builder;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                      withGsonJsonElement:(GsonJsonElement *)jsonElement;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                             withNSNumber:(NSNumber *)number;

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                             withNSString:(NSString *)text;

- (GsonJsonObject *)build;

+ (BrComMobilemindJ2objcJsonJsonBuilder *)create;

@end

J2OBJC_EMPTY_STATIC_INIT(BrComMobilemindJ2objcJsonJsonBuilder)

J2OBJC_FIELD_SETTER(BrComMobilemindJ2objcJsonJsonBuilder, json_, GsonJsonObject *)

FOUNDATION_EXPORT void BrComMobilemindJ2objcJsonJsonBuilder_init(BrComMobilemindJ2objcJsonJsonBuilder *self);

FOUNDATION_EXPORT BrComMobilemindJ2objcJsonJsonBuilder *new_BrComMobilemindJ2objcJsonJsonBuilder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BrComMobilemindJ2objcJsonJsonBuilder *create_BrComMobilemindJ2objcJsonJsonBuilder_init(void);

FOUNDATION_EXPORT BrComMobilemindJ2objcJsonJsonBuilder *BrComMobilemindJ2objcJsonJsonBuilder_create(void);

J2OBJC_TYPE_LITERAL_HEADER(BrComMobilemindJ2objcJsonJsonBuilder)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // JsonBuilder_H
