//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/JsonBuilder.java
//

#include "J2ObjC_source.h"
#include "JsonBuilder.h"
#include "JsonElement.h"
#include "JsonObject.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"

@implementation BrComMobilemindJ2objcJsonJsonBuilder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  BrComMobilemindJ2objcJsonJsonBuilder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (BrComMobilemindJ2objcJsonJsonBuilder *)create {
  return BrComMobilemindJ2objcJsonJsonBuilder_create();
}

- (GsonJsonObject *)build {
  return self->json_;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                 withBrComMobilemindJ2objcJsonJsonBuilder:(BrComMobilemindJ2objcJsonJsonBuilder *)builder {
  [((GsonJsonObject *) nil_chk(json_)) addWithNSString:property withGsonJsonElement:[((BrComMobilemindJ2objcJsonJsonBuilder *) nil_chk(builder)) build]];
  return self;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                      withGsonJsonElement:(GsonJsonElement *)jsonElement {
  [((GsonJsonObject *) nil_chk(json_)) addWithNSString:property withGsonJsonElement:jsonElement];
  return self;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                             withNSString:(NSString *)text {
  [((GsonJsonObject *) nil_chk(json_)) addPropertyWithNSString:property withNSString:text];
  return self;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                             withNSNumber:(NSNumber *)number {
  [((GsonJsonObject *) nil_chk(json_)) addPropertyWithNSString:property withNSNumber:number];
  return self;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                      withJavaLangBoolean:(JavaLangBoolean *)value {
  [((GsonJsonObject *) nil_chk(json_)) addPropertyWithNSString:property withJavaLangBoolean:value];
  return self;
}

- (BrComMobilemindJ2objcJsonJsonBuilder *)addWithNSString:(NSString *)property
                                    withJavaLangCharacter:(JavaLangCharacter *)character {
  [((GsonJsonObject *) nil_chk(json_)) addPropertyWithNSString:property withJavaLangCharacter:character];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGsonJsonObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 2, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 3, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 4, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 5, -1, -1, -1, -1 },
    { NULL, "LBrComMobilemindJ2objcJsonJsonBuilder;", 0x1, 0, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(create);
  methods[2].selector = @selector(build);
  methods[3].selector = @selector(addWithNSString:withBrComMobilemindJ2objcJsonJsonBuilder:);
  methods[4].selector = @selector(addWithNSString:withGsonJsonElement:);
  methods[5].selector = @selector(addWithNSString:withNSString:);
  methods[6].selector = @selector(addWithNSString:withNSNumber:);
  methods[7].selector = @selector(addWithNSString:withJavaLangBoolean:);
  methods[8].selector = @selector(addWithNSString:withJavaLangCharacter:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "json_", "LGsonJsonObject;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "add", "LNSString;LBrComMobilemindJ2objcJsonJsonBuilder;", "LNSString;LGsonJsonElement;", "LNSString;LNSString;", "LNSString;LNSNumber;", "LNSString;LJavaLangBoolean;", "LNSString;LJavaLangCharacter;" };
  static const J2ObjcClassInfo _BrComMobilemindJ2objcJsonJsonBuilder = { "JsonBuilder", "br.com.mobilemind.j2objc.json", ptrTable, methods, fields, 7, 0x1, 9, 1, -1, -1, -1, -1, -1 };
  return &_BrComMobilemindJ2objcJsonJsonBuilder;
}

@end

void BrComMobilemindJ2objcJsonJsonBuilder_init(BrComMobilemindJ2objcJsonJsonBuilder *self) {
  NSObject_init(self);
  self->json_ = new_GsonJsonObject_init();
}

BrComMobilemindJ2objcJsonJsonBuilder *new_BrComMobilemindJ2objcJsonJsonBuilder_init() {
  J2OBJC_NEW_IMPL(BrComMobilemindJ2objcJsonJsonBuilder, init)
}

BrComMobilemindJ2objcJsonJsonBuilder *create_BrComMobilemindJ2objcJsonJsonBuilder_init() {
  J2OBJC_CREATE_IMPL(BrComMobilemindJ2objcJsonJsonBuilder, init)
}

BrComMobilemindJ2objcJsonJsonBuilder *BrComMobilemindJ2objcJsonJsonBuilder_create() {
  BrComMobilemindJ2objcJsonJsonBuilder_initialize();
  return new_BrComMobilemindJ2objcJsonJsonBuilder_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(BrComMobilemindJ2objcJsonJsonBuilder)
