//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/NumberMask.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NumberMask")
#ifdef RESTRICT_NumberMask
#define INCLUDE_ALL_NumberMask 0
#else
#define INCLUDE_ALL_NumberMask 1
#endif
#undef RESTRICT_NumberMask

#if !defined (AppBaseNumberMask_) && (INCLUDE_ALL_NumberMask || defined(INCLUDE_AppBaseNumberMask))
#define AppBaseNumberMask_

@interface AppBaseNumberMask : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)applyWithNSString:(NSString *)text
                   withNSString:(NSString *)pattern;

+ (NSString *)applyReverseWithNSString:(NSString *)text
                          withNSString:(NSString *)pattern;

+ (NSString *)cepWithNSString:(NSString *)text;

+ (NSString *)documentoWithNSString:(NSString *)text;

+ (NSString *)telefoneWithNSString:(NSString *)text;

+ (NSString *)unmaskWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(AppBaseNumberMask)

FOUNDATION_EXPORT void AppBaseNumberMask_init(AppBaseNumberMask *self);

FOUNDATION_EXPORT AppBaseNumberMask *new_AppBaseNumberMask_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AppBaseNumberMask *create_AppBaseNumberMask_init(void);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_applyWithNSString_withNSString_(NSString *text, NSString *pattern);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_applyReverseWithNSString_withNSString_(NSString *text, NSString *pattern);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_unmaskWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_documentoWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_cepWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *AppBaseNumberMask_telefoneWithNSString_(NSString *text);

J2OBJC_TYPE_LITERAL_HEADER(AppBaseNumberMask)

@compatibility_alias BrComMobilemindJ2objcUtilNumberMask AppBaseNumberMask;

#endif

#pragma pop_macro("INCLUDE_ALL_NumberMask")
